[tool.ruff]
line-length = 79
target-version = "py312"
extend-exclude = ["migrations"]

[tool.ruff.format]
indent-style = "space"
quote-style = "double"

[tool.ruff.lint]
select = [
    "A",
    "COM",
    "DJ",
    "E",
    "ERA",
    "F",
    "FIX",
    "I",
    "ISC",
    "N",
    "PTH",
    "RET",
    "RSE",
    "Q",
    "T20",
    "UP",
    "W",
]

[tool.ruff.lint.isort]
force-sort-within-sections = true
order-by-type = false
known-first-party = [
    "api",
    "core",
    "clients",
    "dashboard",
    "hystpanel",
]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"